---
name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: readme
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: debugprint.nvim
          titledatepattern: "%Y-%m-%d"
          shiftheadinglevelby: -1
          dedupsubheadings: false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto generate Vim docs"
          branch: ${{ github.head_ref }}
          file_pattern: 'doc/*'
